import AppKit
import Combine
import SQLite3
import SwiftUI
import XCTest

#if canImport(cmux_DEV)
@testable import cmux_DEV
#elseif canImport(cmux)
@testable import cmux
#endif

@MainActor
final class SessionIndexViewTests: XCTestCase {
    func testClaudeLocalCommandCaveatDisplaysReadableTitle() {
        let entry = makeEntry(
            title: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"
        )

        XCTAssertEqual(
            entry.displayTitle,
            String(localized: "sessionIndex.localCommand", defaultValue: "Local command")
        )
    }

    func testClaudeSlashCommandMarkupDisplaysReadableTitle() {
        let entry = makeEntry(
            title: """
            <command-name>/plugin</command-name>
                        <command-message>plugin</command-message>
                        <command-args>install codex@openai-codex</command-args>
            """
        )

        XCTAssertEqual(entry.displayTitle, "/plugin install codex@openai-codex")
    }

    func testClaudeSlashCommandMarkupIncludesDistinctMessage() {
        let entry = makeEntry(
            title: """
            <command-name>/plugin</command-name>
                        <command-message>install</command-message>
                        <command-args>codex@openai-codex</command-args>
            """
        )

        XCTAssertEqual(entry.displayTitle, "/plugin install codex@openai-codex")
    }

    func testClaudeMetaSlashCommandMarkupDoesNotBecomeTitle() {
        XCTAssertNil(
            SessionEntry.claudeDisplayTitle(
                from: "<command-name>/plugin</command-name>",
                isMeta: true
            )
        )
    }

    func testClaudeResumeCommandPinsConfigDirectoryFromFileURL() {
        let entry = makeEntry(
            sessionId: "claude-session-123",
            title: "resume me",
            fileURL: URL(fileURLWithPath: "/tmp/claude config/projects/-tmp/claude-session-123.jsonl")
        )

        XCTAssertEqual(
            entry.resumeCommand,
            "env CLAUDE_CONFIG_DIR='/tmp/claude config' claude --resume claude-session-123"
        )
    }

    func testClaudeResumeCommandUsesNearestProjectsDirectory() {
        let entry = makeEntry(
            sessionId: "claude-session-123",
            title: "resume me",
            fileURL: URL(
                fileURLWithPath: "/tmp/projects/claude config/projects/-tmp/claude-session-123.jsonl"
            )
        )

        XCTAssertEqual(
            entry.resumeCommand,
            "env CLAUDE_CONFIG_DIR='/tmp/projects/claude config' claude --resume claude-session-123"
        )
    }

    func testCurrentDirectorySetterDoesNotPublishEqualValue() {
        let store = SessionIndexStore()
        var emittedValues: [String?] = []
        let cancellable = store.$currentDirectory
            .dropFirst()
            .sink { emittedValues.append($0) }
        defer { cancellable.cancel() }

        store.setCurrentDirectoryIfChanged("/foo")
        store.setCurrentDirectoryIfChanged("/foo")

        XCTAssertEqual(emittedValues, ["/foo"])
    }

    func testCodexSQLSearchMatchesRolloutTranscriptContent() async throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("cmux-session-index-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let sessionsRoot = tempDir.appendingPathComponent("sessions", isDirectory: true)
        try FileManager.default.createDirectory(at: sessionsRoot, withIntermediateDirectories: true)

        let rolloutURL = sessionsRoot.appendingPathComponent("rollout-codex-transcript-match.jsonl")
        let transcript = """
        {"timestamp":"2026-05-01T09:00:00.000Z","type":"session_meta","payload":{"id":"codex-transcript-match","cwd":"/tmp/project"}}
        {"timestamp":"2026-05-01T09:01:00.000Z","type":"response_item","payload":{"type":"function_call","name":"exec_command","arguments":"{\\"cmd\\":\\"tail -n 80 /tmp/cmux-debug-task-activation-performance-harness.log\\"}","call_id":"call_1"}}
        """
        try transcript.write(to: rolloutURL, atomically: true, encoding: .utf8)

        let stateDB = tempDir.appendingPathComponent("state_5.sqlite")
        try makeCodexStateDatabase(
            at: stateDB,
            rolloutURL: rolloutURL,
            sessionId: "codex-transcript-match"
        )

        let outcome = await SessionIndexStore.loadCodexEntriesForTesting(
            stateDBPath: stateDB.path,
            needle: "/tmp/cmux-debug-task-activation-performance-harness.log",
            offset: 0,
            limit: 10,
            sessionsRoot: sessionsRoot.path
        )

        XCTAssertEqual(outcome.errors, [])
        XCTAssertEqual(outcome.entries.map(\.sessionId), ["codex-transcript-match"])
    }

    func testSectionPopoverHostCoordinatorSkipsHiddenRefreshes() {
        let harness = makeHarness()
        let coordinator = harness.host.makeCoordinator()

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )
        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )

        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 0)
    }

    func testSectionPopoverHostCoordinatorRefreshesOnceWhenPresented() {
        let harness = makeHarness(isPresented: true)
        let coordinator = harness.host.makeCoordinator()
        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 320, height: 240),
            styleMask: [.titled, .closable],
            backing: .buffered,
            defer: false
        )
        let anchor = NSView(frame: NSRect(x: 20, y: 20, width: 160, height: 80))
        window.contentView?.addSubview(anchor)
        coordinator.anchorView = anchor

        defer {
            coordinator.dismiss()
            pumpRunLoop()
            window.orderOut(nil)
        }

        window.makeKeyAndOrderFront(nil)
        window.displayIfNeeded()
        window.contentView?.layoutSubtreeIfNeeded()
        pumpRunLoop()

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )
        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 0)

        coordinator.present()
        pumpRunLoop()

        XCTAssertTrue(coordinator.debugIsPopoverShown)
        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 1)

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )

        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 1)
    }

    private func makeHarness(isPresented: Bool = false) -> SessionPopoverHarness {
        var isPresented = isPresented
        let binding = Binding(
            get: { isPresented },
            set: { isPresented = $0 }
        )
        let section = IndexSection(
            key: .directory("/tmp"),
            title: "tmp",
            icon: .folder,
            entries: []
        )
        let search: SessionSearchFn = { _, _, _, _ in
            SessionIndexStore.SearchOutcome(entries: [], errors: [])
        }
        let loadSnapshot: DirectorySnapshotFn = { cwd in
            DirectorySnapshot(cwd: cwd ?? "", entries: [], errors: [])
        }
        let host = SectionPopoverHost(
            isPresented: binding,
            section: section,
            search: search,
            loadSnapshot: loadSnapshot,
            onResume: nil
        )
        return SessionPopoverHarness(host: host, section: section, search: search, loadSnapshot: loadSnapshot)
    }

    private func makeEntry(
        sessionId: String = UUID().uuidString,
        title: String,
        fileURL: URL? = nil
    ) -> SessionEntry {
        SessionEntry(
            id: UUID().uuidString,
            agent: .claude,
            sessionId: sessionId,
            title: title,
            cwd: nil,
            gitBranch: nil,
            pullRequest: nil,
            modified: Date(timeIntervalSince1970: 0),
            fileURL: fileURL,
            specifics: .claude(model: nil, permissionMode: nil)
        )
    }

    private func pumpRunLoop() {
        RunLoop.current.run(until: Date().addingTimeInterval(0.05))
    }

    private func makeCodexStateDatabase(
        at url: URL,
        rolloutURL: URL,
        sessionId: String
    ) throws {
        var db: OpaquePointer?
        guard sqlite3_open(url.path, &db) == SQLITE_OK, let db else {
            throw SQLiteTestError(message: "open failed")
        }
        defer { sqlite3_close(db) }

        try executeSQL(
            """
            CREATE TABLE threads (
                id TEXT PRIMARY KEY,
                rollout_path TEXT NOT NULL,
                cwd TEXT NOT NULL,
                title TEXT NOT NULL,
                model TEXT,
                git_branch TEXT,
                approval_mode TEXT NOT NULL,
                sandbox_policy TEXT NOT NULL,
                reasoning_effort TEXT,
                first_user_message TEXT NOT NULL,
                updated_at_ms INTEGER,
                archived INTEGER NOT NULL DEFAULT 0
            );
            """,
            db: db
        )

        let sql = """
            INSERT INTO threads (
                id, rollout_path, cwd, title, model, git_branch,
                approval_mode, sandbox_policy, reasoning_effort,
                first_user_message, updated_at_ms, archived
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0);
            """
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK, let stmt else {
            throw SQLiteTestError(message: sqliteMessage(db) ?? "insert prepare failed")
        }
        defer { sqlite3_finalize(stmt) }

        let transient = unsafeBitCast(OpaquePointer(bitPattern: -1), to: sqlite3_destructor_type.self)
        sqlite3_bind_text(stmt, 1, sessionId, -1, transient)
        sqlite3_bind_text(stmt, 2, rolloutURL.path, -1, transient)
        sqlite3_bind_text(stmt, 3, "/tmp/project", -1, transient)
        sqlite3_bind_text(stmt, 4, "unrelated title", -1, transient)
        sqlite3_bind_text(stmt, 5, "gpt-5.5", -1, transient)
        sqlite3_bind_text(stmt, 6, "main", -1, transient)
        sqlite3_bind_text(stmt, 7, "never", -1, transient)
        sqlite3_bind_text(stmt, 8, #"{"type":"danger-full-access"}"#, -1, transient)
        sqlite3_bind_text(stmt, 9, "medium", -1, transient)
        sqlite3_bind_text(stmt, 10, "metadata does not contain the query", -1, transient)
        sqlite3_bind_int64(stmt, 11, 1_777_624_800_000)

        guard sqlite3_step(stmt) == SQLITE_DONE else {
            throw SQLiteTestError(message: sqliteMessage(db) ?? "insert failed")
        }
    }

    private func executeSQL(_ sql: String, db: OpaquePointer) throws {
        guard sqlite3_exec(db, sql, nil, nil, nil) == SQLITE_OK else {
            throw SQLiteTestError(message: sqliteMessage(db) ?? "exec failed")
        }
    }

    private func sqliteMessage(_ db: OpaquePointer) -> String? {
        guard let cString = sqlite3_errmsg(db) else { return nil }
        return String(cString: cString)
    }
}

private struct SessionPopoverHarness {
    let host: SectionPopoverHost
    let section: IndexSection
    let search: SessionSearchFn
    let loadSnapshot: DirectorySnapshotFn
}

private struct SQLiteTestError: Error {
    let message: String
}
