import AppKit
import Combine
import SwiftUI
import XCTest

#if canImport(cmux_DEV)
@testable import cmux_DEV
#elseif canImport(cmux)
@testable import cmux
#endif

@MainActor
final class SessionIndexViewTests: XCTestCase {
    func testClaudeLocalCommandCaveatDisplaysReadableTitle() {
        let entry = makeEntry(
            title: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"
        )

        XCTAssertEqual(
            entry.displayTitle,
            String(localized: "sessionIndex.localCommand", defaultValue: "Local command")
        )
    }

    func testClaudeSlashCommandMarkupDisplaysReadableTitle() {
        let entry = makeEntry(
            title: """
            <command-name>/plugin</command-name>
                        <command-message>plugin</command-message>
                        <command-args>install codex@openai-codex</command-args>
            """
        )

        XCTAssertEqual(entry.displayTitle, "/plugin install codex@openai-codex")
    }

    func testClaudeSlashCommandMarkupIncludesDistinctMessage() {
        let entry = makeEntry(
            title: """
            <command-name>/plugin</command-name>
                        <command-message>install</command-message>
                        <command-args>codex@openai-codex</command-args>
            """
        )

        XCTAssertEqual(entry.displayTitle, "/plugin install codex@openai-codex")
    }

    func testClaudeMetaSlashCommandMarkupDoesNotBecomeTitle() {
        XCTAssertNil(
            SessionEntry.claudeDisplayTitle(
                from: "<command-name>/plugin</command-name>",
                isMeta: true
            )
        )
    }

    func testClaudeResumeCommandPinsConfigDirectoryFromFileURL() {
        let entry = makeEntry(
            sessionId: "claude-session-123",
            title: "resume me",
            fileURL: URL(fileURLWithPath: "/tmp/claude config/projects/-tmp/claude-session-123.jsonl")
        )

        XCTAssertEqual(
            entry.resumeCommand,
            "env CLAUDE_CONFIG_DIR='/tmp/claude config' claude --resume claude-session-123"
        )
    }

    func testClaudeResumeCommandUsesNearestProjectsDirectory() {
        let entry = makeEntry(
            sessionId: "claude-session-123",
            title: "resume me",
            fileURL: URL(
                fileURLWithPath: "/tmp/projects/claude config/projects/-tmp/claude-session-123.jsonl"
            )
        )

        XCTAssertEqual(
            entry.resumeCommand,
            "env CLAUDE_CONFIG_DIR='/tmp/projects/claude config' claude --resume claude-session-123"
        )
    }

    func testCurrentDirectorySetterDoesNotPublishEqualValue() {
        let store = SessionIndexStore()
        var emittedValues: [String?] = []
        let cancellable = store.$currentDirectory
            .dropFirst()
            .sink { emittedValues.append($0) }
        defer { cancellable.cancel() }

        store.setCurrentDirectoryIfChanged("/foo")
        store.setCurrentDirectoryIfChanged("/foo")

        XCTAssertEqual(emittedValues, ["/foo"])
    }

    func testSectionPopoverHostCoordinatorSkipsHiddenRefreshes() {
        let harness = makeHarness()
        let coordinator = harness.host.makeCoordinator()

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )
        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )

        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 0)
    }

    func testSectionPopoverHostCoordinatorRefreshesOnceWhenPresented() {
        let harness = makeHarness(isPresented: true)
        let coordinator = harness.host.makeCoordinator()
        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 320, height: 240),
            styleMask: [.titled, .closable],
            backing: .buffered,
            defer: false
        )
        let anchor = NSView(frame: NSRect(x: 20, y: 20, width: 160, height: 80))
        window.contentView?.addSubview(anchor)
        coordinator.anchorView = anchor

        defer {
            coordinator.dismiss()
            pumpRunLoop()
            window.orderOut(nil)
        }

        window.makeKeyAndOrderFront(nil)
        window.displayIfNeeded()
        window.contentView?.layoutSubtreeIfNeeded()
        pumpRunLoop()

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )
        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 0)

        coordinator.present()
        pumpRunLoop()

        XCTAssertTrue(coordinator.debugIsPopoverShown)
        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 1)

        coordinator.update(
            section: harness.section,
            search: harness.search,
            loadSnapshot: harness.loadSnapshot,
            onResume: nil
        )

        XCTAssertEqual(coordinator.debugRefreshContentCallCount, 1)
    }

    private func makeHarness(isPresented: Bool = false) -> SessionPopoverHarness {
        var isPresented = isPresented
        let binding = Binding(
            get: { isPresented },
            set: { isPresented = $0 }
        )
        let section = IndexSection(
            key: .directory("/tmp"),
            title: "tmp",
            icon: .folder,
            entries: []
        )
        let search: SessionSearchFn = { _, _, _, _ in
            SessionIndexStore.SearchOutcome(entries: [], errors: [])
        }
        let loadSnapshot: DirectorySnapshotFn = { cwd in
            DirectorySnapshot(cwd: cwd ?? "", entries: [], errors: [])
        }
        let host = SectionPopoverHost(
            isPresented: binding,
            section: section,
            search: search,
            loadSnapshot: loadSnapshot,
            onResume: nil
        )
        return SessionPopoverHarness(host: host, section: section, search: search, loadSnapshot: loadSnapshot)
    }

    private func makeEntry(
        sessionId: String = UUID().uuidString,
        title: String,
        fileURL: URL? = nil
    ) -> SessionEntry {
        SessionEntry(
            id: UUID().uuidString,
            agent: .claude,
            sessionId: sessionId,
            title: title,
            cwd: nil,
            gitBranch: nil,
            pullRequest: nil,
            modified: Date(timeIntervalSince1970: 0),
            fileURL: fileURL,
            specifics: .claude(model: nil, permissionMode: nil)
        )
    }

    private func pumpRunLoop() {
        RunLoop.current.run(until: Date().addingTimeInterval(0.05))
    }
}

private struct SessionPopoverHarness {
    let host: SectionPopoverHost
    let section: IndexSection
    let search: SessionSearchFn
    let loadSnapshot: DirectorySnapshotFn
}
